# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: AngularNodeSample SPA
    before: cd angular-node-sample/cloudaland-ui
    init: yarn install
    command: yarn run start

  - name: AngularNodeSample Backend
    before: cd angular-node-sample/cloudaland-bacckend
    init: yarn install
    command: yarn run start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview
  - port: 3000
  
